framework:
  - terraform

quiet: true
compact: true

skip-check:
  # CKV_AZURE_50: "Ensure Virtual Machine extensions are not installed" —
  # not applicable, we don't use VM extensions in this challenge.
  - CKV_AZURE_50
