variable "project" {
  description = "Short project name used in resource naming and tagging."
  type        = string
  default     = "opella"
}

variable "environment" {
  description = "Environment name (dev, prod, ...). Drives naming, tagging, and sizing decisions."
  type        = string
  default     = "dev"
}

variable "location" {
  description = "Azure region, full name, e.g. 'eastus'."
  type        = string
  default     = "eastus"
}

variable "location_short" {
  description = "Short region code used in resource names (e.g. 'eus' for eastus)."
  type        = string
  default     = "eus"
}

variable "address_space" {
  description = "VNET address space for this environment."
  type        = list(string)
  default     = ["10.10.0.0/16"]
}

variable "app_subnet_prefix" {
  description = "CIDR for the app subnet (holds the VM)."
  type        = list(string)
  default     = ["10.10.1.0/24"]
}

variable "data_subnet_prefix" {
  description = "CIDR for the data subnet (has service endpoint to Storage, no VM)."
  type        = list(string)
  default     = ["10.10.2.0/24"]
}

variable "allowed_ssh_cidr" {
  description = "CIDR allowed to SSH into the dev VM. Set to your own IP/32 (or office range) — never leave this as 0.0.0.0/0."
  type        = string
  # Intentionally no default: forces the caller to make an explicit choice
  # instead of silently inheriting an insecure value.
}

variable "vm_size" {
  description = "VM SKU. Defaults to a Free-tier-eligible burstable size."
  type        = string
  default     = "Standard_B1s"
}

variable "admin_username" {
  description = "Admin username for the dev VM."
  type        = string
  default     = "azureadmin"
}

variable "ssh_public_key" {
  description = "SSH public key content for VM login. If left empty, a keypair is generated by Terraform for convenience in dev (not recommended for prod — see environments/prod)."
  type        = string
  default     = ""
}

variable "owner" {
  description = "Tag: person/team responsible for this environment's resources."
  type        = string
  default     = "platform-team"
}

variable "cost_center" {
  description = "Tag: cost center / chargeback code."
  type        = string
  default     = "eng-devops"
}
